# apt-get install libsm-dev
# apt-get install libxaw7-dev
# apt-get install libxcomposite-dev
# apt-get install libxdamage-dev
# apt-get install libxkbfile-dev
# apt-get install libxmu-dev
# apt-get install libxmuu-dev
# apt-get install libxpm-dev
# apt-get install libxres-dev
# apt-get install libxss-dev
# apt-get install libxt-dev
# apt-get install libxtst-dev
# apt-get install libxv-dev
# apt-get install libxvmc-dev
# apt-get install libsfml-dev
# apt-get install libxxf86vm-dev
# apt-get install libxcb-render0-dev
# apt-get install libxcb-render-util0-dev
# apt-get install libxcb-xkb-dev
# apt-get install libxcb-icccm4-dev
# apt-get install libxcb-image0-dev
# apt-get install libxcb-keysyms1-dev
# apt-get install libxcb-randr0-dev
# apt-get install libxcb-shape0-dev
# apt-get install libxcb-sync-dev
# apt-get install libxcb-xfixes0-dev
# apt-get install libxcb-xinerama0-dev
# apt-get install libxcb-dri3-dev
# apt-get install uuid-dev
# apt-get install libxcb-util-dev 
# apt-get install libxcb-util0-dev

yum -y install xkeyboard-config-devel
yum -y install xcb-util-devel
yum -y install systemd-devel
yum -y install libfontenc-devel
yum -y install libXaw-devel
yum -y install libXcomposite-devel
yum -y install libXdmcp-devel
yum -y install libXtst-devel
yum -y install libxkbfile-devel
yum -y install libXres-devel
yum -y install libXScrnSaver-devel
yum -y install libXvMC-devel
yum -y install xorg-x11-xtrans-devel
yum -y install xcb-util-wm-devel
yum -y install xcb-util-image-devel
yum -y install xcb-util-keysyms-devel
yum -y install xcb-util-renderutil-devel
yum -y install libXdamage-devel
yum -y install libXxf86vm-devel
yum -y install libXv-devel
